site_name:        PhysOcean.jl
repo_url:         https://github.com/gher-ulg/PhysOcean.jl
site_description: Utility functions for physical oceanography (properties of seawater, air-sea heat fluxes,...) 
site_author:      Aida Alvera Azcarate, Alexander Barth

theme: mkdocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md